# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/himajin/cpothero

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/himajin/cpothero

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/himajin/cpothero/CMakeFiles /home/himajin/cpothero/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/himajin/cpothero/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

engine.o: engine.cpp.o

.PHONY : engine.o

# target to build an object file
engine.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/engine.cpp.o
.PHONY : engine.cpp.o

engine.i: engine.cpp.i

.PHONY : engine.i

# target to preprocess a source file
engine.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/engine.cpp.i
.PHONY : engine.cpp.i

engine.s: engine.cpp.s

.PHONY : engine.s

# target to generate assembly for a file
engine.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/engine.cpp.s
.PHONY : engine.cpp.s

engine/nteyomi.o: engine/nteyomi.cpp.o

.PHONY : engine/nteyomi.o

# target to build an object file
engine/nteyomi.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/engine/nteyomi.cpp.o
.PHONY : engine/nteyomi.cpp.o

engine/nteyomi.i: engine/nteyomi.cpp.i

.PHONY : engine/nteyomi.i

# target to preprocess a source file
engine/nteyomi.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/engine/nteyomi.cpp.i
.PHONY : engine/nteyomi.cpp.i

engine/nteyomi.s: engine/nteyomi.cpp.s

.PHONY : engine/nteyomi.s

# target to generate assembly for a file
engine/nteyomi.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/engine/nteyomi.cpp.s
.PHONY : engine/nteyomi.cpp.s

engine/one.o: engine/one.cpp.o

.PHONY : engine/one.o

# target to build an object file
engine/one.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/engine/one.cpp.o
.PHONY : engine/one.cpp.o

engine/one.i: engine/one.cpp.i

.PHONY : engine/one.i

# target to preprocess a source file
engine/one.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/engine/one.cpp.i
.PHONY : engine/one.cpp.i

engine/one.s: engine/one.cpp.s

.PHONY : engine/one.s

# target to generate assembly for a file
engine/one.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/engine/one.cpp.s
.PHONY : engine/one.cpp.s

engine/rand_ai.o: engine/rand_ai.cpp.o

.PHONY : engine/rand_ai.o

# target to build an object file
engine/rand_ai.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/engine/rand_ai.cpp.o
.PHONY : engine/rand_ai.cpp.o

engine/rand_ai.i: engine/rand_ai.cpp.i

.PHONY : engine/rand_ai.i

# target to preprocess a source file
engine/rand_ai.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/engine/rand_ai.cpp.i
.PHONY : engine/rand_ai.cpp.i

engine/rand_ai.s: engine/rand_ai.cpp.s

.PHONY : engine/rand_ai.s

# target to generate assembly for a file
engine/rand_ai.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/engine/rand_ai.cpp.s
.PHONY : engine/rand_ai.cpp.s

engine/static.o: engine/static.cpp.o

.PHONY : engine/static.o

# target to build an object file
engine/static.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/engine/static.cpp.o
.PHONY : engine/static.cpp.o

engine/static.i: engine/static.cpp.i

.PHONY : engine/static.i

# target to preprocess a source file
engine/static.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/engine/static.cpp.i
.PHONY : engine/static.cpp.i

engine/static.s: engine/static.cpp.s

.PHONY : engine/static.s

# target to generate assembly for a file
engine/static.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/engine/static.cpp.s
.PHONY : engine/static.cpp.s

eval.o: eval.cpp.o

.PHONY : eval.o

# target to build an object file
eval.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/eval.cpp.o
.PHONY : eval.cpp.o

eval.i: eval.cpp.i

.PHONY : eval.i

# target to preprocess a source file
eval.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/eval.cpp.i
.PHONY : eval.cpp.i

eval.s: eval.cpp.s

.PHONY : eval.s

# target to generate assembly for a file
eval.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/eval.cpp.s
.PHONY : eval.cpp.s

learn.o: learn.cpp.o

.PHONY : learn.o

# target to build an object file
learn.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/learn.cpp.o
.PHONY : learn.cpp.o

learn.i: learn.cpp.i

.PHONY : learn.i

# target to preprocess a source file
learn.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/learn.cpp.i
.PHONY : learn.cpp.i

learn.s: learn.cpp.s

.PHONY : learn.s

# target to generate assembly for a file
learn.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/learn.cpp.s
.PHONY : learn.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

othero.o: othero.cpp.o

.PHONY : othero.o

# target to build an object file
othero.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/othero.cpp.o
.PHONY : othero.cpp.o

othero.i: othero.cpp.i

.PHONY : othero.i

# target to preprocess a source file
othero.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/othero.cpp.i
.PHONY : othero.cpp.i

othero.s: othero.cpp.s

.PHONY : othero.s

# target to generate assembly for a file
othero.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/othero.cpp.s
.PHONY : othero.cpp.s

solve.o: solve.cpp.o

.PHONY : solve.o

# target to build an object file
solve.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/solve.cpp.o
.PHONY : solve.cpp.o

solve.i: solve.cpp.i

.PHONY : solve.i

# target to preprocess a source file
solve.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/solve.cpp.i
.PHONY : solve.cpp.i

solve.s: solve.cpp.s

.PHONY : solve.s

# target to generate assembly for a file
solve.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/solve.cpp.s
.PHONY : solve.cpp.s

test/aitest.o: test/aitest.cpp.o

.PHONY : test/aitest.o

# target to build an object file
test/aitest.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/test/aitest.cpp.o
.PHONY : test/aitest.cpp.o

test/aitest.i: test/aitest.cpp.i

.PHONY : test/aitest.i

# target to preprocess a source file
test/aitest.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/test/aitest.cpp.i
.PHONY : test/aitest.cpp.i

test/aitest.s: test/aitest.cpp.s

.PHONY : test/aitest.s

# target to generate assembly for a file
test/aitest.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/test/aitest.cpp.s
.PHONY : test/aitest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... engine.o"
	@echo "... engine.i"
	@echo "... engine.s"
	@echo "... engine/nteyomi.o"
	@echo "... engine/nteyomi.i"
	@echo "... engine/nteyomi.s"
	@echo "... engine/one.o"
	@echo "... engine/one.i"
	@echo "... engine/one.s"
	@echo "... engine/rand_ai.o"
	@echo "... engine/rand_ai.i"
	@echo "... engine/rand_ai.s"
	@echo "... engine/static.o"
	@echo "... engine/static.i"
	@echo "... engine/static.s"
	@echo "... eval.o"
	@echo "... eval.i"
	@echo "... eval.s"
	@echo "... learn.o"
	@echo "... learn.i"
	@echo "... learn.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... othero.o"
	@echo "... othero.i"
	@echo "... othero.s"
	@echo "... solve.o"
	@echo "... solve.i"
	@echo "... solve.s"
	@echo "... test/aitest.o"
	@echo "... test/aitest.i"
	@echo "... test/aitest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

